services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sqlserver
    restart: always
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD} 
      MSSQL_PID: "Express"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data: